# Generated by Django 3.2.20 on 2023-08-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
