# Generated by Django 3.2.20 on 2023-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_useraccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_balance_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
