# Generated by Django 3.2.20 on 2023-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20230817_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_categories/'),
        ),
    ]
