# Generated by Django 3.2.20 on 2023-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_restaurant_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AddField(
            model_name='sales',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='sales', to='food.Dish'),
        ),
    ]
