# Generated by Django 3.2.20 on 2023-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20230818_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
