# Generated by Django 3.2.20 on 2023-08-18 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_sales_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='discount_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
