# Generated by Django 3.2.20 on 2023-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_sales_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
