# Generated by Django 3.2.20 on 2023-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_sales_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
