# Generated by Django 3.2.20 on 2023-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_dish_on_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='on_sale_price',
            new_name='sale_price',
        ),
    ]
