# Generated by Django 3.2.20 on 2023-08-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_rename_on_sale_price_dish_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
